LojaEsportes.Web/Controllers/NavegaController.cs
using LojaEsportes.Dominio.Entidades;
using LojaEsportes.Dominio.Repositorio;
using System.Web.Mvc;

namespace LojaEsportes.Web.Controllers
{
    public class NavegaController : Controller
    {
        private IRepositorio<Categoria> categoriaRepositorio;

        public NavegaController()
        {
            categoriaRepositorio = new CategoriaRepositorio(new ProdutoContexto());
        }

        public ActionResult Menu()
        {
            var categorias = categoriaRepositorio.GetAll();
            return PartialView(categorias);
        }
    }
}

LojaEsportes.Web/Controllers/ProdutoController.cs
using LojaEsportes.Dominio.Entidades;
using LojaEsportes.Dominio.Repositorio;
using PagedList;
using System.Web.Mvc;

namespace LojaEsportes.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private IRepositorio<Produto> repositorioProduto;

        public ProdutoController()
        {
            repositorioProduto = new ProdutoRepositorio(new ProdutoContexto());
        }
        // GET: Produto
        public ActionResult Catalogo(int? pagina, int? categoria)
        {
            if (categoria == null)
            {
                return View(repositorioProduto.GetAll().ToPagedList(pagina ?? 1, 2));
            }
            else
            {
                return View(repositorioProduto.Get(categoria).ToPagedList(pagina ?? 1, 2));
            }
            
        }
    }
}

LojaEsportes.Web/Views/Navega/Menu.cshtml
@model IEnumerable<LojaEsportes.Dominio.Entidades.Categoria>

@Html.ActionLink("Administrador", "MenuAdministrador", "Administrador", null, new { @class = "btn btn-block btn-default btn-lg" } )

@Html.ActionLink("Home", "Catalogo", "Produto", null, new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var item in Model)
{
    @Html.ActionLink(item.Nome, "Catalogo", "Produto", new { categoria = item.IdCategoria, pagina = 1},
    new
    {
        @class = "btn btn-block btn-default btn-lg" + (item.IdCategoria.ToString() == Request.QueryString["categoria"] ? " btn-primary" : "")
    })
}