LojaEsportes.Web/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LojaEsportes.Web.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Usuário")]
        public string Login { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Senha { get; set; }

        [Display(Name = "Lembrar senha?")]
        public bool LembrarSenha { get; set; }
    }
}

LojaEsportes.Web/Controllers/NavegaController.cs
using LojaEsportes.Dominio.Entidades;
using LojaEsportes.Dominio.Repositorio;
using System.Web.Mvc;

namespace LojaEsportes.Web.Controllers
{
    public class NavegaController : Controller
    {
        private IRepositorio<Categoria> categoriaRepositorio;

        public NavegaController()
        {
            categoriaRepositorio = new CategoriaRepositorio(new ProdutoContexto());
        }

        public ActionResult Menu()
        {
            var categorias = categoriaRepositorio.GetAll();
            return PartialView(categorias);
        }
    }
}

LojaEsportes.Web/Controllers/ProdutoController.cs
using LojaEsportes.Dominio.Entidades;
using LojaEsportes.Dominio.Repositorio;
using PagedList;
using System.Web.Mvc;

namespace LojaEsportes.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private IRepositorio<Produto> repositorioProduto;

        public ProdutoController()
        {
            repositorioProduto = new ProdutoRepositorio(new ProdutoContexto());
        }
        // GET: Produto
        public ActionResult Catalogo(int? pagina, int? categoria)
        {
            if (categoria == null)
            {
                return View(repositorioProduto.GetAll().ToPagedList(pagina ?? 1, 2));
            }
            else
            {
                return View(repositorioProduto.Get(categoria).ToPagedList(pagina ?? 1, 2));
            }
            
        }
    }
}

LojaEsportes.Web/Controllers/UsuarioController.cs
using LojaEsportes.Dominio.Entidades;
using LojaEsportes.Web.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace LojaEsportes.Web.Controllers
{
    public class UsuarioController : Controller
    {
        private ProdutoContexto db = new ProdutoContexto();

        public ActionResult Login(string ReturnUrl)
        {
            ViewBag.ReturnUrl = ReturnUrl;
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string ReturnUrl)
        {
            //logica para validar o login
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (ProdutoContexto dc = new ProdutoContexto())
            {
                var usuario = dc.Usuarios.Where(u => u.Login.Equals(model.Login)).FirstOrDefault();
                if (!Crypto.VerifyHashedPassword(usuario.Senha, model.Senha))
                {
                    usuario = null;
                }
                if (usuario != null)
                {
                    FormsAuthentication.SetAuthCookie(usuario.Login, model.LembrarSenha);

                    if (Url.IsLocalUrl(ReturnUrl))
                    {
                        return Redirect(ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("MenuAdministrador", "Administrador");
                    }
                }
            }
            ModelState.Remove("Senha");
            ModelState.AddModelError("", "Login Inválido");
            return View(model);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Catalogo", "Produto");
        }

        // GET: Usuario
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        // GET: Usuario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUsuario,Login,Senha")] Usuario usuario)
        {
             if (ModelState.IsValid)
            {
                //salvando a senha como um hash
                usuario.Senha = Crypto.HashPassword(usuario.Senha);
                db.Usuarios.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdUsuario,Login,Senha")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuario = db.Usuarios.Find(id);
            db.Usuarios.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaEsportes.Web/Views/Shared/_CatalogoResumo.cshtml
@model LojaEsportes.Dominio.Entidades.Produto

<div class="well">
    @if (Model.Imagem != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" src="@Url.Action("exibirimagem","arquivo", new { id = Model.IdProduto })" width="75" height="75" />
        </div>
    }
    else
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" src="~/Imagens/semimagem.jpg" width="75"
                 height="75" />
        </div>
    }

    <h3>
        <strong>@Model.Nome</strong>
        <span class="pull-right label label-primary">
            @Model.Preco.ToString("c")
        </span>
    </h3>

    @using (Html.BeginForm("AdicionarItemCarrinho", "Carrinho"))
    {
        <div class="pull-right">
            @Html.HiddenFor(produto => produto.IdProduto)
            @Html.Hidden("ReturnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Comprar" />
        </div>
    }

    <span class="lead">@Model.Descricao</span>
</div>

LojaEsportes.Web/Views/Shared/_Error.cshtml
@model System.Web.Mvc.HandleErrorInfo

<h1>Erro</h1>
<h4 class="text-danger">@Model.Exception.Message</h4>

LojaEsportes.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <title>@ViewBag.Title</title>    
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        @*<a class="navbar-brand" href="#">Artigos Esportivos</a>*@
        @Html.ActionLink("Artigos Esportivos", "Catalogo", "Produto", new { area = "" }, new { @class = "navbar-brand" })
        @Html.Partial("_Login")
        @Html.Action("ItensCarrinho", "Carrinho")
    </div>

    <div class="row panel">
        <div id="categorias" class="col-xs-3">
            @Html.Action("Menu", "Navega")            
        </div>
        <div class="col-xs-8">
            @if (TempData["mensagem"] != null)
            {
                <div class="alert alert-success">@TempData["mensagem"]</div>
            }
            @RenderBody()            
        </div>
    </div>
</body>
</html>

LojaEsportes.Web/Views/Shared/_Login.cshtml
@{
    if (Request.IsAuthenticated)
    {
        using (Html.BeginForm("Logout", "Usuario", FormMethod.Post, new { id = "logoutForm", @class = "navbar-left" }))
        {
            <ul class="nav navbar-nav navbar-text navbar-left">
                <li>Bem Vindo @(Request.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "")</li>
            </ul>
            <a class="nav navbar-nav navbar-text navbar-left" href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
        }
    }
    else
    {
        <ul class="nav navbar-nav navbar-left">
            <li>@Html.ActionLink("Login", "Login", "Usuario")</li>
        </ul>
    }
}