LojaEsportes.Web/Controllers/AdministradorController.cs
using LojaEsportes.Dominio.Entidades;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LojaEsportes.Web.Controllers
{
    [Authorize]
    public class AdministradorController : Controller
    {
        private ProdutoContexto db = new ProdutoContexto();

        public ActionResult MenuAdministrador()
        {
            return View();
        }

        // GET: Administrador
        public ActionResult Index()
        {
            var produtos = db.Produtos.Include(p => p.Categoria);
            return View(produtos.ToList());
        }

        // GET: Administrador/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // GET: Administrador/Create
        public ActionResult Create()
        {
            ViewBag.IdCategoria = new SelectList(db.Categorias, "IdCategoria", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProduto,Nome,Descricao,Preco,Imagem,ImagemTipo,IdCategoria")] Produto produto, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var arquivoImagem = new Produto
                    {
                        ImagemTipo = upload.ContentType
                    };
                    using (var leitor = new BinaryReader(upload.InputStream))
                    {
                        arquivoImagem.Imagem = leitor.ReadBytes(upload.ContentLength);
                    }
                    produto.Imagem = arquivoImagem.Imagem;
                    produto.ImagemTipo = arquivoImagem.ImagemTipo;
                }
                db.Produtos.Add(produto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCategoria = new SelectList(db.Categorias, "IdCategoria", "Nome", produto.IdCategoria);
            return View(produto);
        }

        // GET: Administrador/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCategoria = new SelectList(db.Categorias, "IdCategoria", "Nome", produto.IdCategoria);
            return View(produto);
        }
                
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdProduto,Nome,Descricao,Preco,Imagem,ImagemTipo,IdCategoria")] Produto produto, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var arquivoImagem = new Produto
                    {
                        ImagemTipo = upload.ContentType
                    };
                    using (var leitor = new BinaryReader(upload.InputStream))
                    {
                        arquivoImagem.Imagem = leitor.ReadBytes(upload.ContentLength);
                    }
                    produto.Imagem = arquivoImagem.Imagem;
                    produto.ImagemTipo = arquivoImagem.ImagemTipo;
                }
                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                TempData["mensagem"] = string.Format("{0}  : foi atualizado com sucesso", produto.Nome);
                return RedirectToAction("Index");
            }
            ViewBag.IdCategoria = new SelectList(db.Categorias, "CategoriaId", "Nome", produto.IdCategoria);
            return View(produto);
        }

        // GET: Administrador/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

        // POST: Administrador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produto produto = db.Produtos.Find(id);
            db.Produtos.Remove(produto);
            db.SaveChanges();
            TempData["mensagem"] = string.Format("{0}  : foi excluído com sucesso", produto.Nome);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaEsportes.Web/Controllers/ArquivoController.cs
using LojaEsportes.Dominio.Entidades;
using System.Web.Mvc;

namespace LojaEsportes.Web.Controllers
{
    public class ArquivoController : Controller
    {
        // GET: Arquivo
        public ActionResult ExibirImagem(int id)
        {
            using (ProdutoContexto db = new ProdutoContexto())
            {
                var arquivoRetorno = db.Produtos.Find(id);
                return File(arquivoRetorno.Imagem, arquivoRetorno.ImagemTipo);
            }
        }
    }
}

LojaEsportes.Web/Controllers/PermissaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LojaEsportes.Dominio.Entidades;

namespace LojaEsportes.Web.Controllers
{
    public class PermissaoController : Controller
    {
        private ProdutoContexto db = new ProdutoContexto();

        // GET: Permissao
        public ActionResult Index()
        {
            return View(db.Permissoes.ToList());
        }

        // GET: Permissao/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permissao permissao = db.Permissoes.Find(id);
            if (permissao == null)
            {
                return HttpNotFound();
            }
            return View(permissao);
        }

        // GET: Permissao/Create
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPermissao,Nome")] Permissao permissao)
        {
            if (ModelState.IsValid)
            {
                db.Permissoes.Add(permissao);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(permissao);
        }

        // GET: Permissao/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permissao permissao = db.Permissoes.Find(id);
            if (permissao == null)
            {
                return HttpNotFound();
            }
            return View(permissao);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPermissao,Nome")] Permissao permissao)
        {
            if (ModelState.IsValid)
            {
                db.Entry(permissao).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(permissao);
        }

        // GET: Permissao/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permissao permissao = db.Permissoes.Find(id);
            if (permissao == null)
            {
                return HttpNotFound();
            }
            return View(permissao);
        }

        // POST: Permissao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Permissao permissao = db.Permissoes.Find(id);
            db.Permissoes.Remove(permissao);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaEsportes.Web/Controllers/UsuarioController.cs
using LojaEsportes.Dominio.Entidades;
using LojaEsportes.Web.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace LojaEsportes.Web.Controllers
{
    public class UsuarioController : Controller
    {
        private ProdutoContexto db = new ProdutoContexto();

        public ActionResult Login(string ReturnUrl)
        {
            ViewBag.ReturnUrl = ReturnUrl;
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string ReturnUrl)
        {
            //logica para validar o login
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (ProdutoContexto dc = new ProdutoContexto())
            {
                var usuario = dc.Usuarios.Where(u => u.Login.Equals(model.Login)).FirstOrDefault();
                if (!Crypto.VerifyHashedPassword(usuario.Senha, model.Senha))
                {
                    usuario = null;
                }
                if (usuario != null)
                {
                    FormsAuthentication.SetAuthCookie(usuario.Login, model.LembrarSenha);

                    if (Url.IsLocalUrl(ReturnUrl))
                    {
                        return Redirect(ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("MenuAdministrador", "Administrador");
                    }
                }
            }
            ModelState.Remove("Senha");
            ModelState.AddModelError("", "Login Inválido");
            return View(model);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Catalogo", "Produto");
        }

        // GET: Usuario
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        // GET: Usuario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUsuario,Login,Senha")] Usuario usuario)
        {
             if (ModelState.IsValid)
            {
                //salvando a senha como um hash
                usuario.Senha = Crypto.HashPassword(usuario.Senha);
                db.Usuarios.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdUsuario,Login,Senha")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuario = db.Usuarios.Find(id);
            db.Usuarios.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LojaEsportes.Web/Views/Administrador/Create.cshtml
@model LojaEsportes.Dominio.Entidades.Produto

@{
    ViewBag.Title = "Adicionar Produto";
}

<h2>Adicionar Produto</h2>

@using (Html.BeginForm("Create", "Administrador", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            @Html.LabelFor(model => model.IdCategoria, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCategoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Imagem", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Imagem" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

LojaEsportes.Web/Views/Administrador/Delete.cshtml
@model LojaEsportes.Dominio.Entidades.Produto

@{
    ViewBag.Title = "Deletar Produto";
}

<h2>Deletar Produtos</h2>

<h3>Deseja deletar este produto?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (Model.Imagem != null)
        {
            <dt>
                Imagem
            </dt>
            <dd>
                <img src="@Url.Action("ExibirImagem","Arquivo", new { id = Model.IdProduto })" width="150" height="150" />
            </dd>
        }
        else
        {
            <dt>
                Imagem
            </dt>
            <dd>
                <img src="~/Imagens/semimagem.jpg" width="150" height="150" />
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>       

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

LojaEsportes.Web/Views/Administrador/Details.cshtml
@model LojaEsportes.Dominio.Entidades.Produto

@{
    ViewBag.Title = "Detalhes do Produto";
}

<h2>Detalhes do Produto</h2>

<div>    
    <hr />
    <dl class="dl-horizontal">
        @if (Model.Imagem != null)
        {
            <dt>
                Imagem
            </dt>
            <dd>
                <img src="@Url.Action("ExibirImagem","Arquivo", new { id = Model.IdProduto })" width="150" height="150" />
            </dd>
        }
        else
        {
            <dt>
                Imagem
            </dt>
            <dd>
                <img src="~/Imagens/semimagem.jpg" width="150" height="150" />
            </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.Categoria.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>        

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdProduto }) |
    @Html.ActionLink("Voltar", "Index")
</p>

LojaEsportes.Web/Views/Administrador/Edit.cshtml
@model LojaEsportes.Dominio.Entidades.Produto

@{
    ViewBag.Title = "Editar Produto";
}

<h2>Editar Produto</h2>

@using (Html.BeginForm("Edit", "Administrador", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdProduto)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            @Html.LabelFor(model => model.IdCategoria, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCategoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategoria, "", new { @class = "text-danger" })
            </div>
        </div>
        
        @if (Model.Imagem != null)
        {
            <div class="form-group">
                <span class="control-label col-md-2">
                    <strong>
                        Imagem
                        Atual
                    </strong>
                </span>
                <div class="col-md-10">
                    <img src="@Url.Action("ExibirImagem","Arquivo", new { id = Model.IdProduto })" width="150" height="150" />
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                <span class="control-label col-md-2">
                    <strong>
                        Imagem
                        Atual
                    </strong>
                </span>
                <div class="col-md-10">
                    <img src="~/Imagens/semimagem.jpg" width="150" height="150" />
                </div>
            </div>
        } 
        
        <div class="form-group">
            @Html.Label("Nova Imagem", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Imagem" name="upload" />
            </div>
        </div>      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

LojaEsportes.Web/Views/Administrador/Index.cshtml
@model IEnumerable<LojaEsportes.Dominio.Entidades.Produto>

@{
    ViewBag.Title = "Catalogo de Produtos";
}

<h2>Catalogo de Produtos</h2>

<p>
    @Html.ActionLink("Adicionar Produto", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Categoria.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>       
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.IdProduto }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.IdProduto }) |
            @Html.ActionLink("Deletar", "Delete", new { id=item.IdProduto })
        </td>
    </tr>
}
</table>

LojaEsportes.Web/Views/Administrador/MenuAdministrador.cshtml
<img src="~/Imagens/adminsite.jpg" />

<br />

@Html.ActionLink("Administrar Produtos", "Index", "Administrador", null, new { @class = "btn btn-block btn-default btn-lg" })
    
@Html.ActionLink("Administrar Categorias", "Index", "Categoria", null, new { @class = "btn btn-block btn-default btn-lg" })

@Html.ActionLink("Administrar Usuário", "Index", "Usuario", null, new { @class = "btn btn-block btn-default btn-lg" })
@Html.ActionLink("Administrar Permissões", "Index", "Permissao", null, new { @class = "btn btn-block btn-default btn-lg" })
@Html.ActionLink("Administrar Permissões do Usuário", "Index", "UsuarioPermissao", null, new { @class = "btn btn-block btn-default btn-lg" })